apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rolling-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rolling-flask
    spec:
      containers:
        - name: rolling-flask
          image: curtis911/rolling-flask
          imagePullPolicy: Always
          env:
            - name: MASTER_IP
              value: "
            - name: NAMESPACE
              value: "default"